FROM node:20-alpine
WORKDIR /app

COPY app/api/package.json ./app/api/package.json
WORKDIR /app/app/api
RUN npm install && npm install --no-save typescript tsx @types/node

COPY app/api ./

EXPOSE 4000
CMD ["npm", "run", "dev"]
