version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: infra/Dockerfile.api
    ports:
      - "4000:4000"
    env_file:
      - .env

  web:
    build:
      context: .
      dockerfile: infra/Dockerfile.web
    ports:
      - "3000:3000"
    env_file:
      - .env
